[project]
name = "llm-food-grab-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "trueskill>=0.4.5",
]
